Google Docs support, bug fixes, improved output, and more.
Adding Google Docs partial support: download document/presentation/spreadsheets as PDF.

Fixing a bug related to trashing and overwriting: both were not enabled in the sub-folders.

Improving trashing, and fixing some issues related to it.


Improving the output format:
 - More compact output.
 - the size of every file, after its download is completed, is printed in a human-readable format.
 - If the downloaded file needs confirmation, its noticeably indicated immediately.
 - Supporting output in plain text. (Use `--no-colors` or `-nc`.)

Printing the warnings to stderr instead of stdout.

Enable quiet update using `-q -U`.

General code improvements, and better performance.

Improving the comments.

diff --git a/gdrive-dl_unstable b/gdrive-dl_unstable
--- a/gdrive-dl_unstable
+++ b/gdrive-dl_unstable
@@ -3,23 +3,23 @@
 # by NoUrEdDiN : noureddin95@gmail.com
 # License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #
-#  Some documentaions and help phrases are copied, as-is or with change, from GNU grep, GNU wget, and youtube-dl.
+#  Some documentations and help phrases are copied, as-is or with change, from GNU grep, GNU wget, and youtube-dl.
 #
-_VERSION_='2015.11.10-unstable'
+_VERSION_='2015.11.12-unstable'
 _BRANCH_='u' # used for update. where u: unstable, t: testing, s: stable
 
-trash='t' # Trashing Behaviour: 't' for trash (send them to a hidden folder in their parent folder)
-          #                     'r' for remove (remove them completely)
+trash='t' # Trashing Behavior: 't' for trash (send them to a hidden folder in their parent folder)
+          #+                   'r' for remove (remove them completely)
 
 trashbin='TRASH' # a hidden folder created in every folder, to send the trashed files and folders to.
-                 # It must be hidden (starting its name with a dot); So, this dot is included in the code,
+                 # It must be hidden; ie, its name must start with a dot; So, this dot is included in the code,
                  #+ to avoid any problems could happen if missed.
 
 # $_MODE_:
 #   null: normal, # output the pwd & the summary of downloaded file (if any)
 #   1: quiet,     # do not output anything usual (output errors and warning only, if any)
 #   2: verbose,   # output the pwd & everything about the files downloading processes
-#   3: debug,     # output as much informtion as possible
+#   3: debug,     # output as much information as possible
 #
 
 for i in "$@"  # checking debug mode
@@ -42,12 +42,12 @@ trash() # remove files and folders that are no longer online from the local copy
   # $1 is the trashed file or folder
   case "$trash" in
   't')
-    [ "$_MODE_" != "1" ] && echo 'Trashing '$1
+    [ "$_MODE_" != "1" ] && outecho 'Trashing '$1
     mkdir -p ".$trashbin"
     mv -f "$1" ".$trashbin"
     ;;
   'r')
-    [ "$_MODE_" != "1" ] && echo 'Removing '$1
+    [ "$_MODE_" != "1" ] && outecho 'Removing '$1
     rm -rf "$1"
     ;;
   esac
@@ -60,27 +60,33 @@ function download()
   # Download Only files that end in .part, do not exist, or found but with a different size.
   if [ "$_OVERWRITE_" == "1" ]
   then
-    size=$(wget -q "https://docs.google.com/uc?id=${ID}&export=download" --save-headers -O - | head -n 20 | grep Content-Length: | sed 's/[^0-9]*//g')
-    [ "$size" == "" ] && size=$(stat -c %s "${TITLE}" 2>/dev/null) # Some files doesn't have size. We don't redownload them by default.
+    size=$(wget -q "$1" --save-headers -O - | head -n 20 | grep Content-Length: | sed 's/[^0-9]*//g')
+    [ "$size" == "" ] && size=$(stat -c %s "$2" 2>/dev/null) # Some files doesn't have size. We don't redownload them by default.
   fi
-  if [ -f "${TITLE}.part" ] || [ ! -f "${TITLE}" ] || ( [ "$_OVERWRITE_" == "1" ] && [ $(stat -c %s "${TITLE}") -ne $size ] )
+  if [ -f "$2.part" ] || [ ! -f "$2" ] || ( [ "$_OVERWRITE_" == "1" ] && [ $(stat -c %s "$2") -ne $size ] )
   then
     if [ "$_MODE_" == "1" ] # quiet
     then
-      wget -q -c "http://drive.google.com/uc?id=$1&e=download" -O "$2.part" \
+      wget -q -c "$1" -O "$2.part" \
       $([[ "$_RATE_" == "" ]] || echo "--limit-rate=$_RATE_") \
       $([[ "$_WO_" == "" ]] || echo "$_WO_")
     elif [ "$_MODE_" == "2" ] || [ "$_MODE_" == "3" ] # verbose or debug
     then
-      echo Getting "$2"
-      wget -c "http://drive.google.com/uc?id=$1&e=download" -O "$2.part" \
+      outecho "$2"
+      wget -c "$1" -O "$2.part" \
       $([[ "$_RATE_" == "" ]] || echo "--limit-rate=$_RATE_") \
       $([[ "$_WO_" == "" ]] || echo "$_WO_")
     else # neither quiet, nor verbose; i.e., normal
-      echo Getting "$2"
-      wget -nv -c "http://drive.google.com/uc?id=$1&e=download" -O "$2.part" \
+      outget "$2"
+      wget -q -c "$1" -O "$2.part" \
       $([[ "$_RATE_" == "" ]] || echo "--limit-rate=$_RATE_") \
-      $([[ "$_WO_" == "" ]] || echo "$_WO_")
+      $([[ "$_WO_" == "" ]] || echo "$_WO_") &&
+      (
+        if [ $(stat -c %s "$2.part") -le 4000 ] && grep -q '/uc?export=download' "$2.part" 
+        then  outconfirm
+        else  outdone '('$(a=`ls "$2.part" -hs`; echo ${a%% *})')'
+        fi
+      )
     fi && mv "$2"{.part,} # only executed if wget succeeds
   fi
 }
@@ -100,7 +106,7 @@ function chex() # Choose and Exclude
   if [ ${#_CHOOSE_[@]} -ne 0 ] &&  [ ${#_EXCLUDE_[@]} -ne 0 ]
   # if the user used CHOOSE and EXCLUDE at the same time
   then
-    outwarn 'ERROR: ' 'Choose and Exclude are used at the same time.'
+    outwarn ' ERROR: ' 'Choose and Exclude are used at the same time.'
     exit 2
   fi
   
@@ -125,15 +131,55 @@ function chex() # Choose and Exclude
   fi
 }
 
-function output() # bold
+function outecho() # echo the given string, surrounded by bold '*'s
 {
-  tput bold;echo $@;tput sgr0
+  if [ "$_NO_COLORS_" == "1" ]
+  then  echo " * $@ *";
+  else  tput bold;echo -n ' * ';tput sgr0; echo -n "$@"; tput bold;echo ' *';tput sgr0
+  fi
 }
 
-function outwarn() # output warning, bold red for $1, then bold (white) for $2
+function outget() # outecho for "Getting"-messages
 {
-  echo -ne '\e[1;31m'"$1"'\e[m'
-  tput bold;echo "$2";tput sgr0
+  if [ "$_NO_COLORS_" == "1" ]
+  then  echo -n " * Getting $@ * ";
+  else  tput bold;echo -n ' * ';tput sgr0; echo -n "Getting $@"; tput bold;echo -n ' * ';tput sgr0
+  fi
+}
+
+function outdone() # outecho for "Done"-messages
+{
+  if [ "$_NO_COLORS_" == "1" ]
+  then  echo "Done $@ *";
+  else  echo -n "Done $@"; tput bold;echo ' *';tput sgr0
+  fi
+}
+
+function outconfirm() # outecho for "CONFIRM"-messages
+{
+  if [ "$_NO_COLORS_" == "1" ]
+  then  echo 'CONFIRMATION REQUIRED *';
+  else  echo -ne '\e[1;31mCONFIRMATION REQUIRED\e[m'; tput bold;echo ' *';tput sgr0
+  fi
+}
+
+function outbold() # echo in bold
+{
+  if [ "$_NO_COLORS_" == "1" ]
+  then  echo "$@";
+  else  tput bold; echo "$@"; tput sgr0
+  fi
+}
+
+function outwarn() # output warnings to stderr, bold red for $1, then bold for $2
+{
+  if [ "$_NO_COLORS_" == "1" ]
+  then
+    >&2 echo "$1" "$2"
+  else
+    >&2 echo -ne '\e[1;31m'"$1"'\e[m'
+    >&2 tput bold; >&2 echo "$2"; >&2 tput sgr0
+  fi
 }
 function help()
 {
@@ -166,7 +212,7 @@ Downloading Options:
   -cd, --directory=DIR   change to directory DIR; i.e., use it
                          as a place to download in, instead of
                          the current directory.
-  -wo, --wget-option=OPT  if you want to provide specific wget options.
+  -wo, --wget-option=OPT  if you want to provide specific Wget options.
   -o,  --overwrite       if a Drive file is updated, overwrite the local
                          one with the new copy
   -t,  --trash           trash the no-longer-online files and folders
@@ -175,6 +221,7 @@ Output Options:
   -q,  --quiet           suppress all normal output.
   -v,  --verbose         output more information than usual.
   -d,  --debug           output much debugging information.
+  -nc, --no-colors       output in plain text.
 
 Confirming Options:
   to get the big files that Google does not allow to download them
@@ -195,7 +242,7 @@ Notice also that you cannot use both at the same time.
 Not using either '--quiet' or '--verbose' means the normal (default) mode.
 
 Notice that short options cannot be compound, that means you
-cannot use '-qc' as equivalent to '-q -c'; it will not be recognized.
+cannot use '-qc' as equivalent to '-q -c'; It will not be recognized.
 Also, you must use the equal sign '=' with both short and long options,
 if you assign them a value.
 "
@@ -214,7 +261,7 @@ do
       URLS=("${URLS[@]}" "${i//&*/}")
       ;;
     '--confirm'|'-c')
-      # to get the big files that google does not allow to download them directly without confirmation
+      # to get the big files that Google does not allow to download them directly without confirmation
       _CONFIRM_=1
       ;;
     '--confirm='*|'-c='*)
@@ -237,10 +284,13 @@ do
       _AUTO_DETECT_DIRS_=1
       ;;
     '--trash'|'-t')
-      _TRASH_=1
+      export _TRASH_=1
       ;;
     '--overwrite'|'-o')
-      _OVERWRITE_=1
+      export _OVERWRITE_=1
+      ;;
+    '--no-colors'|'-nc')
+      export _NO_COLORS_=1
       ;;
     '--wget-option='*|'-wo='*)
       [ -n "$_WO_" ] && _WO_WARN_=1 || export _WO_="${i#*=}"
@@ -271,16 +321,15 @@ do
       _BRANCH_="${i#*=}"
       ;;
     '--update'|'-U')
-      # to be improved
-      echo -n 'Updating to '
+      [ "$_MODE_" != "1" ] && echo -n 'Updating to '
       t=$(wget -q 'https://raw.githubusercontent.com/noureddin/gdrive-dl/master/VERSION' -O - | grep -- "-${_BRANCH_}")
       if [ -n "$t" ] # t="YYYY.MM.DD-BRANCH master/gdrive-dl_BRANCH" : "version link_to_gdrive-dl"
       then
-        echo ${t%% *}
+        [ "$_MODE_" != "1" ] && echo ${t%% *}
         ( wget -q 'https://raw.githubusercontent.com/noureddin/gdrive-dl/'"${t#* }" -O ${_SCRIPT_} & )
         exit
       else
-        echo 'N/A'
+        [ "$_MODE_" != "1" ] && echo 'N/A'
       fi
       ;;
     '--check-update'|'-cu')
@@ -295,21 +344,21 @@ do
     '--license'|'-L')
       echo 'License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.'
       ;;
-      '--debug'|'-d')
+    '--debug'|'-d')
       ;;
     *)
-      echo "'$i' is not recognized. Try '$(basename "${BASH_SOURCE[0]}") --help' for more information."
+      >&2 echo "'$i' is not recognized. Try '$(basename "${BASH_SOURCE[0]}") --help' for more information."
     ;;
   esac
 done
 
 [ "$_HELP_" == '1' ] && help # to print help only once
 
-[ "$_RATE_WARN_" == '1' ] && outwarn 'WARNING: ' '`--limit` and/or `-l` are used multiple times at the same time; Using the first one.'
+[ "$_RATE_WARN_" == '1' ] && outwarn ' WARNING: ' '`--limit` and/or `-l` are used multiple times at the same time; Using the first one.'
 
-[ "$_MODE_WARN_" ] && outwarn 'WARNING: ' 'Quiet, Verbose, and/or Debug are used at the same time; Using Debug or the first provided one.'
+[ "$_MODE_WARN_" ] && outwarn ' WARNING: ' 'Quiet, Verbose, and/or Debug are used at the same time; Using Debug or the first provided one.'
 
-[ "$_WO_WARN_" == '1' ] && outwarn 'WARNING: ' '`--wget-option` and/or `-wo` are used multiple times at the same time; Using the first one.'
+[ "$_WO_WARN_" == '1' ] && outwarn ' WARNING: ' '`--wget-option` and/or `-wo` are used multiple times at the same time; Using the first one.'
 
 # PRE MAIN _ END READING THE ARGUMENTS
 
@@ -322,15 +371,14 @@ do
     TITLE=$(wget -q "$i" -O -)
     TITLE=${TITLE#*<title>}; TITLE=${TITLE%% - Google Drive</title>*}
     title_escape
-    ID=$(echo ${i//*0B/0B} | sed 's|/.*||')
+    ID=$(echo ${i//*0B/0B} | sed 's|/.*||') # TODO: Google Doc
     download "$ID" "$TITLE"
     ;;
   *folder*)
-    FILE_0=$(wget -q "$i" -O -) # will not be modified
-    FILE_D=$FILE_0 # will be modified, for folders
-    FILE_F=$FILE_0 # will be modified, for files
+    FILE_0=$(wget -q "$i" -O -) # will NOT be modified
+    FILE=$FILE_0 # will be modified
     
-    # If auto_detect_dirs is choosen
+    # If auto_detect_dirs is chosen
     if [ "$_AUTO_DETECT_DIRS_" == "1" ]
     then
       TITLE=${FILE_0#*<title>}; TITLE=${TITLE%%</title>*}
@@ -339,82 +387,91 @@ do
       cd "$TITLE"
       if [ "$_MODE_" != "1" ] # not quiet
       then
-        output Now in "$TITLE/"
+        outbold Now in "$TITLE/"
         NOWPATH="$TITLE/"
       fi
     fi
     
     # Trashing the no-longer-online files and folders first
     [ "$_TRASH_" == "1" ] && # only if wanted
-    ls | while read a
+    for a in *  # http://mywiki.wooledge.org/BashPitfalls#for_i_in_.24.28ls_.2A.mp3.29
     do
-      #echo $FILE_0 | grep 'class="flip-entry-title">'[ \t]*$a[ \t]*'</div>'
-      grep 'class="flip-entry-title">'"[ \t]*$a[ \t]*"'</div>' <<< "$FILE_0" &>/dev/null
+      [ -e "$i" ] || continue
+      # Reversing the title-escaping procedure
+      b="${a//'&'/'&amp;'}"
+      b="${b//\'/'&#39;'}"
+      b="${b//\"/'&quot;'}"
+      b="${b//'['/'\['}"  # for grep
+      b="${b//']'/'\]'}"  # for grep
+      b="${b//'-'/'[-/:]'}"
+      grep 'class="flip-entry-title">'"[ \t]*${b%.part}(.pdf)+[ \t]*"'</div>' <<< "$FILE_0" &>/dev/null
       [ $? -eq 0 ] && continue || [ $? -eq 1 ] && trash "$a"
       # if found; then  ...   else if not found; then ...
     done
     
-    # Downloading files, before folders
-    until [ "$FILE_F" = "${FILE_F#*flip-entry-title\">}" ]
+    # Downloading
+    until [ "$FILE" = "${FILE#*flip-entry-title\">}" ]
     do
-      ID=${FILE_F#*id=\"entry-}; ID=${ID%%\"*}
-      FILE_F=${FILE_F#*flip-entry-title\">}
-      case $FILE_0 in
-      *'/drive.google.com/folderview?id\u003d'$ID*) # is folder
-        continue
-        ;;
-      *'/drive.google.com/uc?id\u003d'$ID*) # is file
-        ;;
-      esac
-      TITLE=${FILE_F%%</div*}
+      ID=${FILE#*id=\"entry-}; ID=${ID%%\"*}
+      FILE=${FILE#*flip-entry-title\">}
+      
+      TITLE=${FILE%%</div*}
       title_escape
       
       chex # Choose and Exclude
       
-      download "$ID" "$TITLE"
+      IDs=("${IDs[@]}" "$ID")
+      TITLEs=("${TITLEs[@]}" "$TITLE")
     done
-    unset FILE_F
+    unset FILE
     
-    
-    # Downloading folders
-    until [ "$FILE_D" = "${FILE_D#*flip-entry-title\">}" ]
+    # Files First !
+    for index in ${!IDs[@]}
     do
-      ID=${FILE_D#*id=\"entry-}; ID=${ID%%\"*}
-      FILE_D=${FILE_D#*flip-entry-title\">}
-      
-      case $FILE_0 in
-      *'/drive.google.com/folderview?id\u003d'$ID*) # is folder
+      case "$FILE_0" in # http://www.labnol.org/internet/direct-links-for-google-drive/28356/
+      *'/docs.google.com/document/d/'${IDs[$index]}*) # Google Document
+        download "https://docs.google.com/document/d/${IDs[$index]}/export?format=pdf" "${TITLEs[$index]}.pdf"
+        IDs[$index]=; TITLEs[$index]=;
         ;;
-      *'/drive.google.com/uc?id\u003d'$ID*) # is file
-        continue
+      *'/docs.google.com/presentation/d/'${IDs[$index]}*) # Google Presentation
+        download "https://docs.google.com/presentation/d/${IDs[$index]}/export/pdf" "${TITLEs[$index]}.pdf"
+        IDs[$index]=; TITLEs[$index]=;
+        ;;
+      *'/docs.google.com/spreadsheets/d/'${IDs[$index]}*) # Google Spreadsheets
+        download "https://docs.google.com/spreadsheets/d/${IDs[$index]}/export?format=pdf" "${TITLEs[$index]}.pdf"
+        IDs[$index]=; TITLEs[$index]=;
+        ;;
+      *'/drive.google.com/uc?id\u003d'${IDs[$index]}*) # Regular File
+        download "https://docs.google.com/uc?id=${IDs[$index]}&export=download" "${TITLEs[$index]}"
+        IDs[$index]=; TITLEs[$index]=;
+        ;;
+      *'/drive.google.com/folderview?id\u003d'${IDs[$index]}*) # Folder; will be downloaded after the files
+        ;;
+      *) # Someting else! ### Remove it form the list
+        IDs[$index]=; TITLEs[$index]=;
         ;;
       esac
-      
-      TITLE=${FILE_D%%</div*}
-      title_escape
-      
-      chex # Choose and Exclude
-      if [ ! -d "$TITLE" ]
-      then
-        mkdir -p "$TITLE"
-      fi
-      
-      cd "$TITLE"
+    done
+    
+    unset FILE_0
+    
+    # Then, Folders
+    for index in ${!IDs[@]}
+    do
+      [ -z "${IDs[$index]}" ] && continue
+      [ ! -d "${TITLEs[$index]}" ] && mkdir -p "${TITLEs[$index]}" ; cd "${TITLEs[$index]}"
       if [ "$_MODE_" != "1" ] # not quiet
       then
-        output Now in "$NOWPATH$TITLE/"
-        NOWPATH="$NOWPATH$TITLE/" ${_SCRIPT_} https://drive.google.com/folderview?id=$ID
+        outbold Now in "$NOWPATH${TITLEs[$index]}/"
+        NOWPATH="$NOWPATH${TITLEs[$index]}/" ${_SCRIPT_} https://drive.google.com/folderview?id=${IDs[$index]}
       else # quiet
-        ${_SCRIPT_} https://drive.google.com/folderview?id=$ID
+        ${_SCRIPT_} https://drive.google.com/folderview?id=${IDs[$index]}
       fi
       cd ..
-      
     done
-    unset FILE_D
-    ;;
+    unset IDs TITLEs
   esac
 done
-
 ## END MAIN ()
 
 
@@ -428,7 +485,7 @@ if [ "$_CONFIRM_" == '1' ]
 then
   grep -lr '/uc?export=download' | while read a
   do
-    output Confirming "$a"
+    outbold Confirming "$a"
     URL=$(grep '/uc?export=download' "$a" | sed 's|.*uc?export=download|uc?export=download|' | sed 's|\".*||')
     perl "${_SCRIPT_%/*}/gdown.pl" 'https://drive.google.com/'"${URL//'&amp;'/'&'}" "$a"
   done
@@ -438,7 +495,7 @@ if [ ${#_CONFIRM_FILE_[@]} -ne 0 ]
 then
   for a in "${_CONFIRM_FILE_[@]}"
   do
-    output Confirming "$a"
+    outbold Confirming "$a"
     URL=$(grep '/uc?export=download' "$a" | sed 's|.*uc?export=download|uc?export=download|' | sed 's|\".*||')
     perl "${_SCRIPT_%/*}/gdown.pl" 'https://drive.google.com/'"${URL//'&amp;'/'&'}" "$a"
   done
